name: Unit & Integration Tests for the APOD JavaFX application.

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 24
        uses: actions/setup-java@v3
        with:
          java-version: '24'
          distribution: 'temurin'
      - name: Build and run tests
        run: mvn clean -Dtest='org.apod.integration.**.*Test' test